update 1-run inline file

diff --git a/0x00-python-hello_world/1-run_inline b/0x00-python-hello_world/1-run_inline
--- a/0x00-python-hello_world/1-run_inline
+++ b/0x00-python-hello_world/1-run_inline
@@ -1,3 +1,7 @@
 #!/bin/bash
 PYCODE="$PYCODE"
+if [ -z "$PYCODE" ]; then
+    echo "Error: PYCODE environment variable is not set."
+    exit 1
+fi
 python3 -c "$PYCODE"
